window_titles:
- 原神
- Genshin Impact
script_folders:
- folder: scripts/common/
  name: 常用脚本
- folder: scripts/careful/
  name: 慎用脚本
log:
  level: Debug
  file: log/giaa.log
delay:
  operation: 120
  view_update: 1100
ocr:
  save_image: true
  image_folder: ocr/
  clean_folder: true
theme: Moonfly
pin_scripts: []
